FROM oraclelinux:7

ARG http_proxy
ARG https_proxy
ARG no_proxy

COPY ol7_optional_development.repo /etc/yum.repos.d/
RUN yum install -y rpmdevtools gcc make automake yum-utils git redhat-lsb-core \
    libpcap-devel libtool gettext-devel && yum clean all

# Set locales
ENV LANG en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
